## Self Study Seminar Presentation
### Course Name - Python for Data Science
### Topic - Numpy
#### Presented By - Ritik Malarya (0901CS191100)
#### Date - 26 october 2021

### What is Numpy?
- NumPy stands for Numerical Python.
- NumPy is the fundamental package for scientific computing in Python.
- NumPy is a Python library used for working with arrays.
- It also has functions for working in domain of linear algebra, fourier transform, and matrices.


### Why use Numpy?

- NumPy provide efficent storage
- It is fast & easy to learn, almost 50X faster than traditional Python lists.
- The array object in NumPy is called ndarray.
- NumPy uses relatively less memory to store data

### Generally, Numpy is written paritally in python,but most of the parts that require fast computation are written in C or C++.

### Installation 
-  For installation, Just simply write pip install numpy in command prompt 

#### How to import Numpy Libraries

- import numpy as np i.e.numpy is usually imported under the np alias.


### Create 1-D, 2-D and 3-D arary

In [14]:
import numpy as np

# 1-Dimensional array
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr1) 
print("--"*50)



# 2-Dimensional array
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr2)
print("--"*50)

# 3-Dimensional array


arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr3)

[ 1  2  3  4  5  6  7  8  9 10]
----------------------------------------------------------------------------------------------------
[[1 2 3 4]
 [5 6 7 8]]
----------------------------------------------------------------------------------------------------
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


### Dimension in arrays

In [16]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])


print("The dimension of array a is ",np.ndim(a))
print("The dimension of array a is ",np.ndim(b))
print("The dimension of array a is ",np.ndim(c))
print("The dimension of array a is ",np.ndim(d))

The dimension of array a is  0
The dimension of array a is  1
The dimension of array a is  2
The dimension of array a is  3


### NumPy arrays indexing

In [30]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0]) #accessing first element

print(arr[1])
print(arr[2])
print(arr[3])
print("-"*40)

print("Accessing 2-d array")


arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr)

print('2nd element on 1st row: ', arr[0, 1])

print("5th elemment on 2nd row",arr[1,4])



1
2
3
4
----------------------------------------
Accessing 2-d array
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2nd element on 1st row:  2
5th elemment on 2nd row 10


### NumPy Array Slicing
- Slicing in python means taking elements from one given index to another given index.

In [36]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5]) # The result includes the start index, but excludes the end index.



#Slice elements from index 4 to the end of the array:
print(arr[4:])

#Slice from the index 3 from the end to index 1 from the end:
print(arr[-3:-1])


# Return every other element.
print(arr[0::2])



[2 3 4 5]
[5 6 7]
[5 6]
[1 3 5 7]


### NumPy Data Types
- i - integer
- b - boolean
- u - unsigned integer
- f - float
- c  - complex float
- m - timedelta
- M - datetime
- O - object
- S - string
- U - unicode string
- V - fixed chunk of memory for other type ( void )

In [48]:
arr = np.array([1,2,3,4,5,6,7,9,11,12,14,34,43])

print(arr.dtype)
print("-"*40)

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype) # unicode string

print("-"*40)

arr = np.array([1, 2, 3, 4], dtype='S')
print(arr.dtype)

int32
----------------------------------------
<U6
----------------------------------------
|S1


### Converting datatype on existing array

- The best way to change the data type of an existing array with the astype() method.

In [50]:
# Change data type from float to integer by using 'i' as parameter value:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)



[1 2 3]
int32


In [52]:
#Change data type from int to Bool by using int as parameter value:

In [55]:
import numpy as np

arr = np.array([1, 0,0,1,1,0])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False False  True  True False]
bool


### NumPy Array Shape
- The shape of an array is the number of elements in each dimension.

In [57]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

#The example above returns (2, 4), which means that the array has 2 dimensions, and each dimension has 4 elements.

(2, 4)


### NumPy Sorting Arrays
- Sorting means putting elements in an ordered sequence.
- The NumPy ndarray object has a function called sort(), that will sort a specified array.

In [62]:
arr = np.array([3, 2, 0, 1])

print("Before Sorting = ",arr)
arr = np.sort(arr)
print("After Sorting = ",arr)



Before Sorting =  [3 2 0 1]
After Sorting =  [0 1 2 3]


In [64]:
# Sort array alphabatically
arr = np.array(['banana', 'cherry', 'apple'])
print("Before Sorting = ",arr)
arr = np.sort(arr)
print("After Sorting = ",arr)

Before Sorting =  ['banana' 'cherry' 'apple']
After Sorting =  ['apple' 'banana' 'cherry']


In [66]:
# Sort a 2-d array
arr = np.array([[3, 2, 4], [5, 0, 1]])

print("Before Sorting = ",arr)
arr = np.sort(arr)
print("After Sorting = ",arr)

Before Sorting =  [[3 2 4]
 [5 0 1]]
After Sorting =  [[2 3 4]
 [0 1 5]]
